# Quiet config (with silencing for noisy libraries)
log_dir: ./logs
default_level: INFO
rotation_size_mb: 5
backup_count: 3
colored_console: true

# External loggers configuration - silence noisy libraries
external_loggers:
  nltk: WARNING  # Only show WARNING and above from NLTK
  urllib3: WARNING  # NLTK uses urllib3 for downloads
  requests: WARNING  # Sometimes used for downloads
