name: Interactive Debug Session

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -e ".[dev,test,ci,doc]"
          python -m pip install PyYAML
          echo "Installed packages:"
          pip list

      - name: Prepare test directories
        run: |
          mkdir -p reports/html
          mkdir -p htmlcov
          mkdir -p junit
          chmod -R 777 reports htmlcov junit

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true  # Only you can connect
